// @flow

export default {
    NEW_TAB_REQUESTED: 'NEW_TAB_REQUESTED',
    SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
    CLOSE_TAB: 'CLOSE_TAB',
    LOAD_URL_REQUESTED: 'LOAD_URL_REQUESTED',
    WEBVIEW_LOAD_STARTED: 'WEBVIEW_LOAD_STARTED',
    WEBVIEW_LOAD_FINISHED: 'WEBVIEW_LOAD_FINISHED',
    TAB_UPDATE_REQUESTED: 'TAB_UPDATE_REQUESTED',
    GO_BACK_REQUESTED: 'GO_BACK_REQUESTED',
    GO_FORWARD_REQUESTED: 'GO_FORWARD_REQUESTED',
    RELOAD_TAB_REQUESTED: 'RELOAD_TAB_REQUESTED',
    STOP_TAB_LOADING_REQUESTED: 'STOP_TAB_LOADING_REQUESTED',
    TAB_NAVIGATION_COMPLETE: 'TAB_NAVIGATION_COMPLETE'
};
